# Generated by Django 4.1.3 on 2022-11-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
