# Generated by Django 4.1.3 on 2022-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_min_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
