# Generated by Django 4.1.3 on 2022-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.CharField(default='niemand', max_length=30),
            preserve_default=False,
        ),
    ]
