# Generated by Django 4.1.3 on 2022-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default='Niemand', max_length=1000),
            preserve_default=False,
        ),
    ]
