# Generated by Django 4.1.3 on 2022-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_bid_bid_title_item_comment_commen_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='title_item',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commen_title',
            field=models.CharField(max_length=1000),
        ),
    ]
