# Generated by Django 4.1.3 on 2022-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_commen_title_comment_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_user',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bidder',
            field=models.CharField(default='Xander', max_length=1000),
        ),
    ]
