# Generated by Django 4.1.3 on 2022-11-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_comment_comment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(default='geen', max_length=1000),
            preserve_default=False,
        ),
    ]
