# Generated by Django 4.1.3 on 2022-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_comment_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_user',
            field=models.CharField(default='onnog', max_length=1000),
            preserve_default=False,
        ),
    ]
